sonar.projectKey=gryphus-lab_coreui-free-react-admin-template
sonar.organization=gryphus-lab


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=coreui-free-react-admin-template
sonar.projectVersion=1.0.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.tsx,src/**/*.spec.tsx
sonar.exclusions=*/node_modules/**,**/dist/**,build/**,.yarn/**
sonar.language=ts
sonar.typescript.file.suffixes=.ts,.tsx
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8